### ISSUE TITLE
Add `init` function

### ISSUE THREAD

**Issue by ghost** [gulpjs/undertaker-registry#1]
As of undertakers [latest commit](https://github.com/phated/undertaker/commit/e7bf5b3602e522e75d7bf964d8b70d9e7fa26a32), this repo needs an `init` function so that gulp-hub can create the `DefaultRegistry()` and pass the validation check without the error `AssertionError: Custom registry must have 'init' function`

**Comment by phated** [comment]
As you probably already noticed, this has been handled and published as 0.0.3

**Comment by ghost** [comment]
Ya sorry, I was trying to track down the issue when I noticed that gulp-hub#4.0 branch didn't have the new 0.0.3 code. then saw the issue on gulp-hub with the registry-init branch. All quite confusing in the end
